FROM php:7.2-fpm

RUN apt-get update && \
        apt-get install -y \
        git \
        curl \
        libzip-dev \
        libmemcached-dev \
        libz-dev \
        libjpeg-dev \
        libssl-dev \
        libmcrypt-dev \
	&& apt-get clean \
    && rm -r /var/lib/apt/lists/*

RUN docker-php-ext-install \
        mbstring \
        curl \
        json \
        pdo_mysql \
        zip \
        opcache \
    && pecl install xdebug \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install bcmath \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-enable zip \
    && docker-php-ext-enable xdebug

#Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
	composer selfupdate