FROM php:7.2-fpm

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	git \
	curl \
	libzip-dev \
	libmemcached-dev \
	libz-dev \
	libjpeg-dev \
	libssl-dev \
	libmycrypt-dev \
	sshpass \

#Install Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

#Install ZIP
RUN pecl install zip && docker-php-ext-enable zip

#Install the PHP Mycrypt Extension
RUN docker-php-ext-install mycrypt

#Install the PHP pdo_mysql Extension
RUN docker-php-ext-install pdo_mysql

#Install composer
RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && rm -rf /var/lib/apt/lists/*